// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJnBrecMPlbJBGWMwBPFYhDuh2cgPmTk',
    appId: '1:1054731279094:web:ff1491352d98dbfafaaad7',
    messagingSenderId: '1054731279094',
    projectId: 'nammamadurai-22c18',
    authDomain: 'nammamadurai-22c18.firebaseapp.com',
    storageBucket: 'nammamadurai-22c18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM5qVn3BpVg3XEBu0zk6NaRAIJ-Hgxgzk',
    appId: '1:1054731279094:android:11b15835f1ed2c87faaad7',
    messagingSenderId: '1054731279094',
    projectId: 'nammamadurai-22c18',
    storageBucket: 'nammamadurai-22c18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5igXZ66OmvlXTWCCwRDwcJ8YvXlxy9Pg',
    appId: '1:1054731279094:ios:31e0b4c740c6e2d0faaad7',
    messagingSenderId: '1054731279094',
    projectId: 'nammamadurai-22c18',
    storageBucket: 'nammamadurai-22c18.appspot.com',
    iosClientId: '1054731279094-k0h0t9pa0ckq98hpodbgfs59pdapvf3r.apps.googleusercontent.com',
    iosBundleId: 'com.nammamadurai.nammamadurai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5igXZ66OmvlXTWCCwRDwcJ8YvXlxy9Pg',
    appId: '1:1054731279094:ios:d8fb36e530960917faaad7',
    messagingSenderId: '1054731279094',
    projectId: 'nammamadurai-22c18',
    storageBucket: 'nammamadurai-22c18.appspot.com',
    iosClientId: '1054731279094-ked8h14uc7cv8jhrn6r00soaoebusnqa.apps.googleusercontent.com',
    iosBundleId: 'com.nammamadurai.nammamadurai.RunnerTests',
  );
}
